### ISSUE TITLE
沙发！顺便问一个问题

### ISSUE THREAD

**Issue by panpeng0014** [yuweiguocn/SquareLoading#1]
请问为什么你能在onMeasure方法里面执行对孩子的layout操作呢？

**Comment by yuweiguocn** [comment]
View的工作流程就是measure、layout、draw会调用对应的onMeasure、onLayout、onDraw
measureChildren方法会调用子VIew的onMeasure，这样子View的测量就完成了，然后就可以对子View进行布局（layout）了。我们也可以在onLayout方法中对子View进行布局，这里我们只是空实现。

比如，LinearLayout是在onLayout方法中对子View进行布局的
```
 @Override
    protected void onLayout(boolean changed, int l, int t, int r, int b) {
        if (mOrientation == VERTICAL) {
            layoutVertical(l, t, r, b);
        } else {
            layoutHorizontal(l, t, r, b);
        }
    }
```

不知道我说清楚没有，希望不要误人子弟。
