### ISSUE TITLE
xCount和yCount换一些数字就会出现一些bug

### ISSUE THREAD

**Issue by DearZack** [yuweiguocn/SquareLoading#2]
getNextAnimChild()这个函数感觉不太看得懂啊，有点混乱，出现这个bug应该也是这个函数的问题

**Comment by yuweiguocn** [comment]
谢谢，是我疏忽了，已经改过了。

**Comment by yuweiguocn** [comment]
这个方法用于获取下一个要执行动画的View的index，例如
![image](https://cloud.githubusercontent.com/assets/4308480/20555499/78b440d8-b19d-11e6-93d9-410ec912c58c.png)

第一个要执行动画的View的index为8，第二个为4，第三个为0，依次为：8、4、0、9、5、1、10、6、2、11、7、3。反向动画则顺序相反。

**Comment by DearZack** [comment]
整明白了

**Comment by DearZack** [comment]
278行直接改成这样，是不是可以更好理解一点这个函数：
index = i - mXCount;
一开始没看明白你的函数，后来不看你的函数自己写了一遍这个函数，发现就这一行的区别

**Comment by yuweiguocn** [comment]
赞，是的，写完了没检查代码导致的，多谢！
